name: gh-pages-build
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '16.x' # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
          npm run export

      - name: Archive build output
        run: tar --dereference --hard-dereference --directory out/ -cvf artifact.tar .

      - uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

  deploy:
    needs: build
    permissions:
      contents: 'read'
      pages: 'write'
      id-token: 'write'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v1
        name: ghpages-deploy
